//! High-level Rust types that wrap the raw `vst3` crate FFI layer.
//!
//! Shared value types live in `tutti-plugin-types`; this module owns the
//! VST3-specific extensions (`Vst3Sample`, event tagged-unions, parameter
//! info with VST3 flags, `BusInfo`, `PluginInfo`).

use smallvec::SmallVec;

mod audio;
mod events;
mod info;
mod transport;

pub use audio::Vst3Sample;
pub(crate) use audio::K_SAMPLE_64_INT;
pub(crate) use events::{from_c_event, to_c_event};
pub use events::{
    note_expression_to_vst3, note_expression_type_from_id, note_expression_type_to_id,
    vst3_to_chord, vst3_to_note_expression, vst3_to_note_expression_int,
    vst3_to_note_expression_text, vst3_to_scale, ChordEvent, ChordValue, DataEvent, EventHeader,
    LegacyMidiCcOutEvent, NoteExpressionIntValue, NoteExpressionIntValueEvent, NoteExpressionText,
    NoteExpressionTextEvent, NoteExpressionValueEvent, NoteOffEvent, NoteOnEvent,
    PolyPressureEvent, ScaleEvent, ScaleValue, TextRef, Vst3Event, K_CHORD_EVENT, K_DATA_EVENT,
    K_LEGACY_MIDI_CC_OUT_EVENT, K_NOTE_EXPRESSION_INT_VALUE_EVENT, K_NOTE_EXPRESSION_TEXT_EVENT,
    K_NOTE_EXPRESSION_VALUE_EVENT, K_NOTE_OFF_EVENT, K_NOTE_ON_EVENT, K_POLY_PRESSURE_EVENT,
    K_SCALE_EVENT,
};
pub use info::{
    automation_state, keyswitch_type, note_expression_flags, parameter_flags, physical_ui_type,
    prefetchable_support, BusInfo, Vst3KeyswitchInfo, Vst3NoteExpressionInfo, Vst3ParameterInfo,
};
pub use transport::{process_context_flags, to_process_context};

// Re-exports of the cross-format vocabulary, including the note-expression
// enum + value (the ABI conversion to VST3's `typeId` lives in `events`).
pub use tutti_plugin_types::{
    AudioBuffer, BufferPtrs, EditorCapabilities, EditorSize, MidiEvent, NoteExpressionType,
    NoteExpressionValue, ParameterChanges, ParameterPoint, ParameterQueue, Sample, TransportInfo,
    WindowHandle,
};

/// Events and parameter changes emitted by the plugin during one call to
/// [`Vst3Instance::process`](crate::Vst3Instance::process).
///
/// Owned variant. Off-RT callers (tests, offline render) can keep this
/// around. RT callers should use [`ProcessOutputRef`] instead — it
/// borrows the instance's pooled buffers without copying.
pub struct ProcessOutput {
    /// MIDI events generated by the plugin (e.g. arpeggiator output).
    pub midi_events: SmallVec<[MidiEvent; 64]>,
    /// Parameter changes reported via `outputParameterChanges` — typically
    /// used by plugins with host-visible automation readouts.
    pub parameter_changes: ParameterChanges,
}

/// Borrowing view of the plugin's per-block output. Points into the
/// `Vst3Instance`'s pooled return-value buffers — valid until the next
/// `process` call, which clears them in place. RT-safe.
#[derive(Debug, Clone, Copy)]
pub struct ProcessOutputRef<'a> {
    pub midi_events: &'a [MidiEvent],
    pub parameter_changes: &'a ParameterChanges,
}

impl<'a> ProcessOutputRef<'a> {
    /// Snapshot into an owned [`ProcessOutput`]. Allocates; off-RT only.
    pub fn to_owned(self) -> ProcessOutput {
        ProcessOutput {
            midi_events: self.midi_events.iter().copied().collect(),
            parameter_changes: self.parameter_changes.clone(),
        }
    }
}

/// Identity + capability descriptor for a plugin class.
///
/// Populated by [`Vst3Loaded::probe`](crate::Vst3Loaded::probe) /
/// [`Vst3Loaded::load`](crate::Vst3Loaded::load); builder methods on this
/// type are exposed so hosts that wrap multiple plugin formats can
/// construct equivalent `PluginInfo` values by hand.
#[derive(Debug, Clone)]
pub struct PluginInfo {
    /// Unique id, formatted as `vst3.<CID>` by this crate.
    pub id: String,
    pub name: String,
    pub vendor: String,
    pub version: String,
    /// Input channel count on bus 0.
    pub num_inputs: usize,
    /// Output channel count on bus 0.
    pub num_outputs: usize,
    /// Per-bus channel counts for every audio **input** bus, in bus-index
    /// order. `input_bus_channels[0]` mirrors [`num_inputs`](Self::num_inputs)
    /// (the main bus); subsequent entries are aux/sidechain input buses.
    /// Empty when the plugin has no audio input buses.
    pub input_bus_channels: Vec<usize>,
    /// Per-bus channel counts for every audio **output** bus, in bus-index
    /// order. `output_bus_channels[0]` mirrors
    /// [`num_outputs`](Self::num_outputs) (the main bus); subsequent entries
    /// are aux output buses. Empty when the plugin has no audio output buses.
    pub output_bus_channels: Vec<usize>,
    /// `true` if the plugin exposes at least one input event bus.
    pub has_midi_input: bool,
    /// `true` if the plugin exposes at least one output event bus (emits MIDI
    /// the host can read back).
    pub has_midi_output: bool,
    /// `true` if the plugin advertises `kSample64` processing.
    pub supports_f64: bool,
}

impl PluginInfo {
    pub fn new(id: impl Into<String>, name: impl Into<String>) -> Self {
        Self {
            id: id.into(),
            name: name.into(),
            vendor: String::new(),
            version: String::new(),
            num_inputs: 2,
            num_outputs: 2,
            input_bus_channels: Vec::new(),
            output_bus_channels: Vec::new(),
            has_midi_input: false,
            has_midi_output: false,
            supports_f64: false,
        }
    }

    pub fn vendor(mut self, vendor: impl Into<String>) -> Self {
        self.vendor = vendor.into();
        self
    }

    pub fn version(mut self, version: impl Into<String>) -> Self {
        self.version = version.into();
        self
    }

    pub fn audio_io(mut self, inputs: usize, outputs: usize) -> Self {
        self.num_inputs = inputs;
        self.num_outputs = outputs;
        self
    }

    /// Record the full per-bus channel layout (one entry per audio bus, in
    /// bus-index order). The main bus (`[0]`) is expected to match
    /// [`num_inputs`](Self::num_inputs) / [`num_outputs`](Self::num_outputs).
    pub fn bus_channels(
        mut self,
        input_bus_channels: Vec<usize>,
        output_bus_channels: Vec<usize>,
    ) -> Self {
        self.input_bus_channels = input_bus_channels;
        self.output_bus_channels = output_bus_channels;
        self
    }

    /// Total input channels across all audio input buses (main + aux). Falls
    /// back to [`num_inputs`](Self::num_inputs) when no per-bus layout was
    /// recorded (single-bus legacy).
    pub fn total_input_channels(&self) -> usize {
        if self.input_bus_channels.is_empty() {
            self.num_inputs
        } else {
            self.input_bus_channels.iter().sum()
        }
    }

    /// Total output channels across all audio output buses (main + aux). Falls
    /// back to [`num_outputs`](Self::num_outputs) when no per-bus layout was
    /// recorded (single-bus legacy).
    pub fn total_output_channels(&self) -> usize {
        if self.output_bus_channels.is_empty() {
            self.num_outputs
        } else {
            self.output_bus_channels.iter().sum()
        }
    }

    pub fn midi(mut self, has_midi: bool) -> Self {
        self.has_midi_input = has_midi;
        self
    }

    pub fn midi_output(mut self, has_midi_output: bool) -> Self {
        self.has_midi_output = has_midi_output;
        self
    }

    pub fn f64_support(mut self, supports: bool) -> Self {
        self.supports_f64 = supports;
        self
    }
}

#[cfg(test)]
mod plugin_info_bus_tests {
    use super::PluginInfo;

    /// No per-bus layout recorded → totals fall back to the flat bus-0 counts
    /// (single-bus legacy behaviour).
    #[test]
    fn empty_bus_layout_falls_back_to_flat_counts() {
        let info = PluginInfo::new("vst3.x", "X").audio_io(2, 2);
        assert!(info.input_bus_channels.is_empty());
        assert!(info.output_bus_channels.is_empty());
        assert_eq!(info.total_input_channels(), 2);
        assert_eq!(info.total_output_channels(), 2);
    }

    /// Multi-bus layout → totals sum every bus; bus-0 entry mirrors the flat
    /// count.
    #[test]
    fn multi_bus_layout_sums_all_buses() {
        // stereo main + mono sidechain in; stereo main + stereo aux out.
        let info = PluginInfo::new("vst3.x", "X")
            .audio_io(2, 2)
            .bus_channels(vec![2, 1], vec![2, 2]);
        assert_eq!(info.input_bus_channels, vec![2, 1]);
        assert_eq!(info.output_bus_channels, vec![2, 2]);
        assert_eq!(info.total_input_channels(), 3);
        assert_eq!(info.total_output_channels(), 4);
        // Main bus mirrors the flat count.
        assert_eq!(info.input_bus_channels[0], info.num_inputs);
        assert_eq!(info.output_bus_channels[0], info.num_outputs);
    }
}
