//! The two measured values the trait's own signatures name.
//!
//! [`AudioUnit::set_sample_rate`](crate::AudioUnit::set_sample_rate) takes a
//! [`SampleRate`] and [`AudioUnit::tail`](crate::AudioUnit::tail) returns a
//! [`Tail`]. Both are `tutti-types`' and are re-exported here, unchanged, so
//! that a consumer reading the trait can reach them from one place.
//!
//! # Why they were not moved down, and what it costs
//!
//! Every other piece of the contract — the tower, the buffers, `Signal`,
//! `Setting` — is *defined* here, which is what makes this crate the floor.
//! These two are the exception, and the exception is deliberate:
//!
//! - **`SampleRate` cannot move alone.** It is one of ~30 units generated by
//!   `tutti_types::value::units`' `unit_newtype!` / `unit_ordered!` /
//!   `unit_bounded!` macros, it implements that module's `Unit` marker, and its
//!   `nyquist`/`nyquist_scaled` return `Hz`. Relocating it means relocating
//!   `Hz`, `Unit` and the macro machinery — that is the whole units vocabulary,
//!   and its own docs record that living outside `value::units` was the
//!   *previous* mistake, paid for in hand-written operator impls.
//! - **`Tail::Finite` carries `Samples`**, and `Samples::to_seconds` returns
//!   `Seconds` at a `SampleRate`. Moving `Tail` therefore drags `Samples`,
//!   which drags the same two units; `Samples` also has 158 references inside
//!   `tutti-types` alone, in the `latency` and `tail` graph walks.
//!
//! The cost is that this crate is not `no_std`: `tutti-types` is std-only (34
//! `std::` uses across 11 files, including `std::io::Result` on the public
//! `AudioOut::finalize` signature). That was measured rather than assumed, and
//! it costs nothing, because **nothing in Tutti is `no_std`** — a settled
//! decision (2026-09-02), not an accident. `fundsp-tutti` used to claim to be,
//! behind a `std` feature; the claim was false (its no-default-features build
//! failed with five errors in `latency/`, a Tutti addition using `Vec` and
//! `std::array::from_fn` unguarded), nothing ever selected it, and the feature
//! was removed rather than repaired. So there is no `no_std` configuration in
//! the engine for this crate's `tutti-types` edge to break.
//!
//! Everything else about the leaf property holds: `tutti-types` names no other
//! `tutti` crate, so the graph stays acyclic and `fundsp-tutti` sits cleanly on
//! top of both.

pub use tutti_types::{SampleRate, Samples, Tail};
