//-----------------------------------------------------------------------------
// Versioning / resource strings for the audio-correctness probe.
//-----------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Generated by cmake.
#include "projectversion.h"

#define stringOriginalFilename "audio-probe.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "Tutti Audio Correctness Probe (64Bit)"
#else
#define stringFileDescription "Tutti Audio Correctness Probe"
#endif
#define stringCompanyWeb "https://github.com/PoHsuanLai/Tutti"
#define stringCompanyEmail "mailto:none@example.com"
#define stringCompanyName "Tutti"
#define stringLegalCopyright "Test fixture — not a distributable audio plug-in"
#define stringLegalTrademarks "VST is a trademark of Steinberg Media Technologies GmbH"
